if: branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
os:
  - linux
  - windows
language: node_js
node_js:
  - '14'
  - '12'
  - '10'
after_success: npm run coverage
deploy:
  edge: true
  provider: npm
  on:
    tags: true
